### ISSUE TITLE
Installation fails due to `http` package dependency

### ISSUE THREAD

**Issue by danielemontecchi** [hillelcoren/flutter-redux-starter#21]
I have a problem during installation. Fails immediately because of the version of the `http` package:

```
Running "flutter packages get" in hillelcoren-flutter-redux-starter...
Because every version of flutter_driver from sdk depends on http 0.12.0 and flutter_redux_starter depends on http ^0.11.3+17, flutter_driver from sdk is forbidden.
So, because flutter_redux_starter depends on flutter_driver any from sdk, version solving failed.

pub get failed (1)
```

Updating the version of `http` at `^0.12.0`, in the `pubspec.yaml` file, I get another error:

```
Running "flutter packages get" in hillelcoren-flutter-redux-starter...
Because every version of flutter_driver from sdk depends on analyzer 0.33.0 and built_value_generator >=5.5.5 depends on analyzer ^0.32.1, flutter_driver from sdk is incompatible with built_value_generator >=5.5.5.
So, because nerv depends on both built_value_generator ^6.1.4 and flutter_driver any from sdk, version solving failed.

pub get failed (1)
```

The result of `flutter --version` is:
```
Flutter 0.9.4 • channel beta • https://github.com/flutter/flutter.git
Framework • revision f37c235c32 (3 weeks ago) • 2018-09-25 17:45:40 -0400
Engine • revision 74625aed32
Tools • Dart 2.1.0-dev.5.0.flutter-a2eb050044
```

**Comment by danibjor** [comment]
Strange. Had that error too before I found the right combination of dependency versions. What os/version?

Looks like we are on the same version of flutter:
```
Daniels-iMac:hbs_client daniel$ flutter --version
Flutter 0.9.4 • channel beta • https://github.com/flutter/flutter.git
Framework • revision f37c235c32 (3 weeks ago) • 2018-09-25 17:45:40 -0400
Engine • revision 74625aed32
Tools • Dart 2.1.0-dev.5.0.flutter-a2eb050044
```

pubspec.yaml
```
dependencies:
  flutter:
    sdk: flutter
  flutter_redux: ^0.5.2
  redux_logging: ^0.3.0
  http: ^0.11.3+17
  path_provider: ^0.4.1
  shared_preferences: ^0.4.3
  built_value: ^6.1.4
  built_collection: ^4.0.0
  memoize: ^2.0.0
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  built_value_generator: ^6.1.4
```

**Comment by danielemontecchi** [comment]
No, I'm sorry. The dependencies on the `pubspec.yaml` file are identical: 
```
name: eva
version: 0.0.1
description:
author:
homepage: 

dependencies:
  flutter:
    sdk: flutter
  flutter_redux: ^0.5.2
  redux_logging: ^0.3.0
  http: ^0.11.3+17
  path_provider: ^0.4.1
  shared_preferences: ^0.4.3
  built_value: ^6.1.4
  built_collection: ^4.0.0
  memoize: ^2.0.0
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  built_value_generator: ^6.1.4
  
flutter:
  uses-material-design: true
```
I work with Mac OS P:
![Installation](https://i.imgur.com/zxMxcuM.png)

Even with a new installation, the error is the same:
![Installation](https://i.imgur.com/jywSiou.png)

**Comment by danibjor** [comment]
whats the output if you run the command
`flutter doctor -v`

**Comment by danielemontecchi** [comment]
```
[✓] Flutter (Channel beta, v0.9.4, on Mac OS X 10.14 18A391, locale it-IT)
    • Flutter version 0.9.4 at /Users/dmontecchi/Library/flutter
    • Framework revision f37c235c32 (3 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/dmontecchi/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/dmontecchi/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.28.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.19.0

[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by danibjor** [comment]
Saw a similiar issue where `flutter_driver` caused problems from `sdk` (this looks like a flutter issue, and not this project) https://github.com/flutter/flutter/issues/18937
try `flutter channel beta` `flutter doctor` `flutter packages get`

**Comment by danielemontecchi** [comment]
Commenting on these lines in the `pubspec.yaml` file I was able to install correctly the app without errors <span class="emoji-outer emoji-sizer"><span class="emoji-inner" style="background: url(chrome-extension://immhpnclomdloikkpcefncmfgjbkojmh/emoji-data/sheet_twitter_32.png);background-position:16.039952996474735% 71.97414806110459%;background-size:5418.75% 5418.75%" data-codepoints="1f389"></span></span><span class="emoji-outer emoji-sizer"><span class="emoji-inner" style="background: url(chrome-extension://immhpnclomdloikkpcefncmfgjbkojmh/emoji-data/sheet_twitter_32.png);background-position:16.039952996474735% 71.97414806110459%;background-size:5418.75% 5418.75%" data-codepoints="1f389"></span></span>:
```
dev_dependencies:
#  flutter_driver:
#    sdk: flutter
#  flutter_test:
#    sdk: flutter
  build_runner: ^1.0.0
  built_value_generator: ^6.1.4
```
